### DISCUSSION TITLE
Wiki changes

### DISCUSSION THREAD

**Discussion by Daniel-Valentine** [ferritreader/ferrit#32] [Ideas]
Please propose changes you'd like to see in the wiki here.

**Comment by Traction6131** [comment]
I would probably add a docker compose file to [the installation part](https://github.com/libbacon/ferrit/wiki/Building,-Installation,-and-Deployment). I'm just making one for my instance, but we could also use the one in the repo, it looks pretty good (adding the environment tag would probably be nice).
Edit:

```
version: "3.8"

services:
  web:
    image: ferrit:latest
    restart: always
    container_name: ferrit
    ports:
      - 8080:8080
    environment:
      - FERRIT_DEFAULT_THEME=gold
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "--tries=1", "http://localhost:8080/settings"]
      interval: 5m
      timeout: 3s
```
This for example, saying that you could do that after building the image (until it's published), since build in docker compose files was sometimes wierd for me.

Plus, I know it's not recommended rn, but if you wanted, but you could add my instance:
- https://snoo.habedieeh.re/
- http://snoo.habeehrhadazsw3izbrbilqajalfyqqln54mrja3iwpqxgcuxnus7eid.onion/
